rabbitmq1:
  image: rabbitmq:3.6.0
  ports:
    - "5672:5672"
rabbitmq2:
  image: rabbitmq:3.6.0
  links:
    - rabbitmq1
  ports:
    - "5673:5672"
rabbitmq3:
  image: rabbitmq:3.6.0
  links:
    - rabbitmq1
  ports:
    - "5674:5672"
management:
  image: rabbitmq:3.6.0-management
  links:
    - rabbitmq1
    - rabbitmq2
    - rabbitmq3
  ports:
    - "15672:15672"
